# Generated by Django 5.0.1 on 2024-01-31 15:56

# stores/migrations/0003_auto_20240131_2126.py

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'sample-data.json'
CITY = 'Visakhapatnam'

def load_data(apps, schema_editor):
    print("Starting data loading...")
    Store = apps.get_model('stores', 'Store')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        try:
            objects = json.load(datafile)
            elements = objects.get('features', [])  # Updated to match your data structure

            for obj in elements:
                print(f"Processing object: {obj}")
                objType = obj.get('type', '')
                if objType == 'Feature':
                    tags = obj.get('properties', {})
                    name = tags.get('name', 'N/A')

                    coordinates = obj.get('geometry', {}).get('coordinates', [])
                    longitude, latitude = coordinates[0], coordinates[1]
                    location = fromstr(f'POINT({latitude} {longitude})', srid=4326)

                    housenumber = tags.get('addr:housenumber', 'N/A')
                    street = tags.get('addr:street', 'N/A')
                    postcode = tags.get('addr:postcode', 'N/A')
                    address = f'{housenumber}, {street}, {postcode}'

                    store_type = tags.get('shop', 'N/A')
                    phone = tags.get('phone', 'N/A')

                    print(f"Creating Store: {name}")
                    Store(
                        name=name,
                        latitude=latitude,
                        longitude=longitude,
                        location=location,
                        store_type=store_type,
                        phone=phone[:100],
                        address=address[:100],
                        city=CITY,
                    ).save()
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON: {e}")

    print("Data loading completed.")

class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]

    class Meta:
        managed = False
